### ISSUE TITLE
Unable to compile with Makefile

### ISSUE THREAD

**Issue by ghost** [lordmulder/msws-rng#1]
I'm unable to compile the program using makefile, as it tells me that the file ``crt0.o`` cannot be found.
However, for some strange reason. compiling with ``g++`` on its own works.

**Comment by lordmulder** [comment]
Well, the Makefile is really minimal, nothing fancy.

So I suggest you figure out which specific option in the *default* `CXXFLAGS` set by the Makefile causes the problem for you :smirk:

Option `-static` would be a good candidate.

If build fails *only* with option `-static`, then this would indicate that your C++ compiler doesn't support "static" build.
